name: amary_story
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.3.0
  http_parser: ^4.1.2
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  chucker_flutter: ^1.8.3
  image_picker: ^1.0.4
  image: ^4.5.4
  mime: ^2.0.0
  google_maps_flutter: ^2.12.0
  google_maps_flutter_web: ^0.5.12
  geocoding: ^3.0.0
  location: ^5.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

fonts:
  - family: IBMPlexSansCondensed
    fonts:
      - asset: assets/fonts/IBMPlexSansCondensed-Bold.ttf
        weight: 700
      - asset: assets/fonts/IBMPlexSansCondensed-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/IBMPlexSansCondensed-Medium.ttf
        weight: 500
      - asset: assets/fonts/IBMPlexSansCondensed-Regular.ttf
        weight: 400
      - asset: assets/fonts/IBMPlexSansCondensed-Light.ttf
        weight: 300
      - asset: assets/fonts/IBMPlexSansCondensed-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/IBMPlexSansCondensed-Thin.ttf
        weight: 100
